<?php

return [
	'add' => 'Add',
	'add_users' => 'Add members to the mailing list',
	'analytics' => 'Analytics',
	'search' => 'Search',
	'clear_search' => 'Clear Search',
	'content_analytics' => 'Content Analytics',
	'country' => 'Country',
	'country_name' => 'Country',
	'created_at' => 'Registered',
	'csv_export' => 'Export to CSV',
	'current_month' => 'Curr. Month',
	'delim_char' => 'Delimiter Character',
	'email' => 'Email',
	'enclose_char' => 'Enclosure Character',
	'export' => 'Export',
	'export_all' => 'Export All',
	'export_to_csv' => 'Export to CSV',
	'first_name' => 'First Name',
	'from_date' => 'From',
	'google_analytics' => 'Google Analytics',
	'id' => 'ID',
	'import' => 'Import',
	'language_code' => 'Language',
	'language_name' => 'Name',
	'last_name' => 'Last Name',
	'literature_reviews_language' => 'Literature Highlights by Language',
	'mailing_list' => 'Mailing List',
	'marketing_preferences' => 'Want Emails',
	'new_users_by_country' => 'New Members by Country',
	'new_users_by_country' => 'New Members by Country',
	'new_users_by_region' => 'New Members by Region',
	'new_users_by_region' => 'New Members by Region',
	'only_want_emails' => 'Only Members who want emails',
	'send_emails' => 'Send emails  ',
	'podcast_episode_language' => 'Podcast Episodes by Language',
	'podcast_playlist_language' => 'Podcast Playlists by Language',
	'previous_month' => 'Prev. Month',
	'publications_language' => 'Publications by Language',
	'region' => 'Region',
	'remove' => 'Remove',
	'remove_users' => 'Remove members from the mailing list',
	'reset' => 'Reset',
	'resource_language' => 'Resources by Language',
	'select_file' => 'Select CSV',
	'to_date' => 'To',
	'total' => 'Total',
	'total_users_by_country' => 'Total Members by Country',
	'total_users_by_country' => 'Total Members by Country',
	'total_users_by_region' => 'Total Members by Region',
	'total_users_by_region' => 'Total Members by Region',
	'user_import' => 'Member Import from CSV',
	'user_search' => 'Member Search',
	'users' => 'Members',
	'users_by_country' => 'Members by Country',
	'webinar_language' => 'Webinars by Language',
	'course' => 'Course Title',
	'question' => 'Evalution Question',
	'user_name' => 'Member Name',
	'response_type' => 'Response Type',
	'response' => 'Response',



	'error_file_not_csv' => 'File not in CSV format',
	'error_incorrect_column_count' => 'Incorrect number of columns, invalid file format',
	'error_invalid_file' => 'File format not valid or file not selected, data not uploaded',
	'error_already_exists' => 'already exists',
	'error_invalid_email' => '- invalid email address',
];
